# dependabot.yml file with updates
# disabled for Docker and limited for npm

version: 2
updates:
  # Configuration for Dockerfile
  - package-ecosystem: "docker"
    directory: "/packages/app-backend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/packages/app-frontend"
    schedule:
      interval: "weekly"

  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@white-rabbit*"
