flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags:
    - name: app-frontend
      paths:
        - packages/app-frontend
    - name: components
      paths:
        - packages/business-logic
    - name: desktop-render
      paths:
        - packages/desktop-render
