version: '3.8'
services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.21-latest
    restart: always
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
