version: '3.8'
services:
  envoy:
    image: envoyproxy/envoy-alpine:v1.21-latest
    restart: always
    ports:
      - "10000:10000"
      - "9901:9901"
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml

  app-backend-graphql:
    build: "./packages/app-backend-graphql"
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MIKRO_ORM_USER=postgres
      - MIKRO_ORM_PASSWORD=test1234
      - MIKRO_ORM_HOST=host.docker.internal

  app-frontend:
    build: "./packages/app-frontend"
    restart: always
    ports:
      - "4010:80"
