/* eslint-disable */
// @generated by protobuf-ts 2.7.0 with parameter eslint_disable,ts_nocheck,optimize_code_size
// @generated from protobuf file "record.proto" (package "whiterabbit.record", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { RecordService } from "./record";
import type { Commands } from "./record";
import type { Command } from "./record";
import type { Record } from "./record";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RecordPage } from "./record";
import type { FindPageRequest } from "./shared";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { RecordResponse } from "./record";
import type { StringValue } from "./google/protobuf/wrappers";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service whiterabbit.record.RecordService
 */
export interface IRecordServiceClient {
  /**
   * @generated from protobuf rpc: findOne(google.protobuf.StringValue) returns (whiterabbit.record.RecordResponse);
   */
  findOne(
    input: StringValue,
    options?: RpcOptions
  ): UnaryCall<StringValue, RecordResponse>;
  /**
   * @generated from protobuf rpc: findPage(whiterabbit.shared.FindPageRequest) returns (whiterabbit.record.RecordPage);
   */
  findPage(
    input: FindPageRequest,
    options?: RpcOptions
  ): UnaryCall<FindPageRequest, RecordPage>;
  /**
   * @generated from protobuf rpc: findAll(google.protobuf.StringValue) returns (stream whiterabbit.record.Record);
   */
  findAll(
    input: StringValue,
    options?: RpcOptions
  ): ServerStreamingCall<StringValue, Record>;
  /**
   * @generated from protobuf rpc: handle(whiterabbit.record.Command) returns (whiterabbit.record.RecordResponse);
   */
  handle(
    input: Command,
    options?: RpcOptions
  ): UnaryCall<Command, RecordResponse>;
  /**
   * @generated from protobuf rpc: handleAll(whiterabbit.record.Commands) returns (stream whiterabbit.record.RecordResponse);
   */
  handleAll(
    input: Commands,
    options?: RpcOptions
  ): ServerStreamingCall<Commands, RecordResponse>;
}
/**
 * @generated from protobuf service whiterabbit.record.RecordService
 */
export class RecordServiceClient implements IRecordServiceClient, ServiceInfo {
  typeName = RecordService.typeName;
  methods = RecordService.methods;
  options = RecordService.options;
  constructor(private readonly _transport: RpcTransport) {}
  /**
   * @generated from protobuf rpc: findOne(google.protobuf.StringValue) returns (whiterabbit.record.RecordResponse);
   */
  findOne(
    input: StringValue,
    options?: RpcOptions
  ): UnaryCall<StringValue, RecordResponse> {
    const method = this.methods[0],
      opt = this._transport.mergeOptions(options);
    return stackIntercept<StringValue, RecordResponse>(
      "unary",
      this._transport,
      method,
      opt,
      input
    );
  }
  /**
   * @generated from protobuf rpc: findPage(whiterabbit.shared.FindPageRequest) returns (whiterabbit.record.RecordPage);
   */
  findPage(
    input: FindPageRequest,
    options?: RpcOptions
  ): UnaryCall<FindPageRequest, RecordPage> {
    const method = this.methods[1],
      opt = this._transport.mergeOptions(options);
    return stackIntercept<FindPageRequest, RecordPage>(
      "unary",
      this._transport,
      method,
      opt,
      input
    );
  }
  /**
   * @generated from protobuf rpc: findAll(google.protobuf.StringValue) returns (stream whiterabbit.record.Record);
   */
  findAll(
    input: StringValue,
    options?: RpcOptions
  ): ServerStreamingCall<StringValue, Record> {
    const method = this.methods[2],
      opt = this._transport.mergeOptions(options);
    return stackIntercept<StringValue, Record>(
      "serverStreaming",
      this._transport,
      method,
      opt,
      input
    );
  }
  /**
   * @generated from protobuf rpc: handle(whiterabbit.record.Command) returns (whiterabbit.record.RecordResponse);
   */
  handle(
    input: Command,
    options?: RpcOptions
  ): UnaryCall<Command, RecordResponse> {
    const method = this.methods[3],
      opt = this._transport.mergeOptions(options);
    return stackIntercept<Command, RecordResponse>(
      "unary",
      this._transport,
      method,
      opt,
      input
    );
  }
  /**
   * @generated from protobuf rpc: handleAll(whiterabbit.record.Commands) returns (stream whiterabbit.record.RecordResponse);
   */
  handleAll(
    input: Commands,
    options?: RpcOptions
  ): ServerStreamingCall<Commands, RecordResponse> {
    const method = this.methods[4],
      opt = this._transport.mergeOptions(options);
    return stackIntercept<Commands, RecordResponse>(
      "serverStreaming",
      this._transport,
      method,
      opt,
      input
    );
  }
}
