/* eslint-disable */
// @generated by protobuf-ts 2.7.0 with parameter eslint_disable,ts_nocheck,server_generic,client_none,optimize_code_size
// @generated from protobuf file "access-item.proto" (package "whiterabbit.accessItem", syntax proto3)
// tslint:disable
// @ts-nocheck
import { RpcInputStream } from "@protobuf-ts/runtime-rpc";
import { AccessItem } from "./access-item";
import { FindAllRequest } from "./shared";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service whiterabbit.accessItem.AccessItemService
 */
export interface IAccessItemService<T = ServerCallContext> {
  /**
   * @generated from protobuf rpc: findAll(whiterabbit.shared.FindAllRequest) returns (stream whiterabbit.accessItem.AccessItem);
   */
  findAll(
    request: FindAllRequest,
    responses: RpcInputStream<AccessItem>,
    context: T
  ): Promise<void>;
}
