/* eslint-disable */
// @generated by protobuf-ts 2.7.0 with parameter eslint_disable,ts_nocheck,server_generic,client_none,optimize_code_size
// @generated from protobuf file "group.proto" (package "whiterabbit.group", syntax proto3)
// tslint:disable
// @ts-nocheck
import { RpcInputStream } from "@protobuf-ts/runtime-rpc";
import { Commands } from "./group";
import { Command } from "./group";
import { GroupPage } from "./group";
import { FindPageRequest } from "./shared";
import { GroupResponse } from "./group";
import { StringValue } from "./google/protobuf/wrappers";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service whiterabbit.group.GroupService
 */
export interface IGroupService<T = ServerCallContext> {
  /**
   * @generated from protobuf rpc: findOne(google.protobuf.StringValue) returns (whiterabbit.group.GroupResponse);
   */
  findOne(request: StringValue, context: T): Promise<GroupResponse>;
  /**
   * @generated from protobuf rpc: findPage(whiterabbit.shared.FindPageRequest) returns (whiterabbit.group.GroupPage);
   */
  findPage(request: FindPageRequest, context: T): Promise<GroupPage>;
  /**
   * @generated from protobuf rpc: handle(whiterabbit.group.Command) returns (whiterabbit.group.GroupResponse);
   */
  handle(request: Command, context: T): Promise<GroupResponse>;
  /**
   * @generated from protobuf rpc: handleAll(whiterabbit.group.Commands) returns (stream whiterabbit.group.GroupResponse);
   */
  handleAll(
    request: Commands,
    responses: RpcInputStream<GroupResponse>,
    context: T
  ): Promise<void>;
}
