/* eslint-disable */
// @generated by protobuf-ts 2.7.0 with parameter eslint_disable,ts_nocheck,server_generic,client_none,optimize_code_size
// @generated from protobuf file "journal.proto" (package "whiterabbit.journal", syntax proto3)
// tslint:disable
// @ts-nocheck
import { Commands } from "./journal";
import { Command } from "./journal";
import { RpcInputStream } from "@protobuf-ts/runtime-rpc";
import { Journal } from "./journal";
import { JournalPage } from "./journal";
import { FindPageRequest } from "./shared";
import { JournalResponse } from "./journal";
import { StringValue } from "./google/protobuf/wrappers";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service whiterabbit.journal.JournalService
 */
export interface IJournalService<T = ServerCallContext> {
  /**
   * @generated from protobuf rpc: findOne(google.protobuf.StringValue) returns (whiterabbit.journal.JournalResponse);
   */
  findOne(request: StringValue, context: T): Promise<JournalResponse>;
  /**
   * @generated from protobuf rpc: findPage(whiterabbit.shared.FindPageRequest) returns (whiterabbit.journal.JournalPage);
   */
  findPage(request: FindPageRequest, context: T): Promise<JournalPage>;
  /**
   * @generated from protobuf rpc: findAll(google.protobuf.StringValue) returns (stream whiterabbit.journal.Journal);
   */
  findAll(
    request: StringValue,
    responses: RpcInputStream<Journal>,
    context: T
  ): Promise<void>;
  /**
   * @generated from protobuf rpc: handle(whiterabbit.journal.Command) returns (whiterabbit.journal.JournalResponse);
   */
  handle(request: Command, context: T): Promise<JournalResponse>;
  /**
   * @generated from protobuf rpc: handleAll(whiterabbit.journal.Commands) returns (stream whiterabbit.journal.JournalResponse);
   */
  handleAll(
    request: Commands,
    responses: RpcInputStream<JournalResponse>,
    context: T
  ): Promise<void>;
}
