/* eslint-disable */
// @generated by protobuf-ts 2.7.0 with parameter eslint_disable,ts_nocheck,server_generic,client_none,optimize_code_size
// @generated from protobuf file "record.proto" (package "whiterabbit.record", syntax proto3)
// tslint:disable
// @ts-nocheck
import { RpcInputStream } from "@protobuf-ts/runtime-rpc";
import { Commands } from "./record";
import { Command } from "./record";
import { RecordPage } from "./record";
import { FindPageRequest } from "./shared";
import { RecordResponse } from "./record";
import { StringValue } from "./google/protobuf/wrappers";
import { ServerCallContext } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service whiterabbit.record.RecordService
 */
export interface IRecordService<T = ServerCallContext> {
  /**
   * @generated from protobuf rpc: findOne(google.protobuf.StringValue) returns (whiterabbit.record.RecordResponse);
   */
  findOne(request: StringValue, context: T): Promise<RecordResponse>;
  /**
   * @generated from protobuf rpc: findPage(whiterabbit.shared.FindPageRequest) returns (whiterabbit.record.RecordPage);
   */
  findPage(request: FindPageRequest, context: T): Promise<RecordPage>;
  /**
   * @generated from protobuf rpc: handle(whiterabbit.record.Command) returns (whiterabbit.record.RecordResponse);
   */
  handle(request: Command, context: T): Promise<RecordResponse>;
  /**
   * @generated from protobuf rpc: handleAll(whiterabbit.record.Commands) returns (stream whiterabbit.record.RecordResponse);
   */
  handleAll(
    request: Commands,
    responses: RpcInputStream<RecordResponse>,
    context: T
  ): Promise<void>;
}
