// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import "@vue/runtime-core";

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    ABreadcrumb: typeof import("ant-design-vue/es")["Breadcrumb"];
    ABreadcrumbItem: typeof import("ant-design-vue/es")["BreadcrumbItem"];
    AButton: typeof import("ant-design-vue/es")["Button"];
    AConfigProvider: typeof import("ant-design-vue/es")["ConfigProvider"];
    ADatePicker: typeof import("ant-design-vue/es")["DatePicker"];
    ADivider: typeof import("ant-design-vue/es")["Divider"];
    ADropdown: typeof import("ant-design-vue/es")["Dropdown"];
    AForm: typeof import("ant-design-vue/es")["Form"];
    AFormItem: typeof import("ant-design-vue/es")["FormItem"];
    AInput: typeof import("ant-design-vue/es")["Input"];
    ALayout: typeof import("ant-design-vue/es")["Layout"];
    ALayoutContent: typeof import("ant-design-vue/es")["LayoutContent"];
    ALayoutFooter: typeof import("ant-design-vue/es")["LayoutFooter"];
    ALayoutHeader: typeof import("ant-design-vue/es")["LayoutHeader"];
    ALayoutSider: typeof import("ant-design-vue/es")["LayoutSider"];
    AList: typeof import("ant-design-vue/es")["List"];
    AListItem: typeof import("ant-design-vue/es")["ListItem"];
    AListItemMeta: typeof import("ant-design-vue/es")["ListItemMeta"];
    AMenu: typeof import("ant-design-vue/es")["Menu"];
    AMenuItem: typeof import("ant-design-vue/es")["MenuItem"];
    AModal: typeof import("ant-design-vue/es")["Modal"];
    ASelect: typeof import("ant-design-vue/es")["Select"];
    ASpace: typeof import("ant-design-vue/es")["Space"];
    ASpin: typeof import("ant-design-vue/es")["Spin"];
    ASwitch: typeof import("ant-design-vue/es")["Switch"];
    ATag: typeof import("ant-design-vue/es")["Tag"];
    ATextarea: typeof import("ant-design-vue/es")["Textarea"];
    ATypographyParagraph: typeof import("ant-design-vue/es")["TypographyParagraph"];
    ATypographyText: typeof import("ant-design-vue/es")["TypographyText"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
  }
}

export {};
